project:
  type: website

website:
  title: "IIQ2013"
  reader-mode: true
  repo-url: https://github.com/OO-UU/workbook_IIQ2013
  search: 
    location: sidebar
    type: textbox
  back-to-top-navigation: false
  
  navbar:
    left:
      - href: home.qmd
        text: "Inicio"
      - href: ./e_prop/intro.qmd
        text: "Ejercicios propuestos"

  sidebar: 
    - title: "Ejercicios propuestos"
      logo: logo.png
      contents:
        - ./e_prop/intro.qmd
        - text: "---"
        - text: "Transporte de fluidos"
        - section: "Tuberías y bombas"
          contents: 
            - ./e_prop/00_bernoulli/e00_1.qmd
            - ./e_prop/00_bernoulli/e00_2.qmd
            - ./e_prop/00_bernoulli/e00_3.qmd
        - section: "Fluidos no Newtonianos"
          contents:
            - ./e_prop/01_FNN/e01_1.qmd
        - section: "Agitación y mezclado"
          contents:
            - ./e_prop/02_agitacion/e02_1.qmd
            - ./e_prop/02_agitacion/e02_2.qmd

format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css
    toc: true
    grid: 
      body-width: 900px
      sidebar-width: 300px
      margin-width: 200px
      gutter-width: 1em
