project:
  type: website

website:
  title: "IIQ2013"
  reader-mode: true
  repo-url: https://github.com/OO-UU/workbook_IIQ2013
  search: 
    location: sidebar
    type: textbox
  back-to-top-navigation: false
  
  navbar:
    left:
      - href: home.qmd
        text: "Inicio"
      - href: ./e_prop/intro.qmd
        text: "Ejercicios propuestos"

  sidebar: 
    - title: "Ejercicios propuestos"
      logo: logo.png
      contents:
        - ./e_prop/intro.qmd
        - text: "---"
        - text: "Transporte de fluidos"
        - section: "Tuberías y bombas"
          contents: 
            - ./e_prop/00_bernoulli/e00_1.qmd
            - ./e_prop/00_bernoulli/e00_2.qmd
            - ./e_prop/00_bernoulli/e00_3.qmd
        - section: "Fluidos no Newtonianos"
          contents:
            - ./e_prop/01_FNN/e01_1.qmd
        - section: "Agitación y mezclado"
          contents:
            - ./e_prop/02_agitacion/e02_1.qmd
            - ./e_prop/02_agitacion/e02_2.qmd
        - section: "Fluidos compresibles y compresores"
          contents:
           - ./e_prop/03_compresibles/e03_1.qmd
           - ./e_prop/03_compresibles/e03_2.qmd
        - text: "Transferencia de calor"
        - section: "ICDT"
          contents:
           - ./e_prop/04_ICDT/e04_1.qmd
        - section: "Transferencia de calor en estanques agitados"
          contents:
           - ./e_prop/05_tc-agitacion/e05_1.qmd
        - section: "ICTC"
          contents: 
           - ./e_prop/06_ICTC/e06_1.qmd
           - ./e_prop/06_ICTC/e06_2.qmd
        - section: "Superficies extendidas"
          contents: 
           - ./e_prop/07_ICC/e07_1.qmd
           - ./e_prop/07_ICC/e07_2.qmd
           - ./e_prop/07_ICC/e07_3.qmd
        - section: "Evaporadores"
          contents: 
           - ./e_prop/08_evaporadores/e08_1.qmd
           - ./e_prop/08_evaporadores/e08_2.qmd
           - ./e_prop/08_evaporadores/e08_3.qmd

format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css
    toc: true
    grid: 
      body-width: 900px
      sidebar-width: 300px
      margin-width: 200px
      gutter-width: 1em
