---
title: 'Ejercicio 1: Bernoulli'
format:
    html: 
      code-copy: true
      code-fold: true
      code-links: 
        - text: "Descargar Jupyter (.ipynb)"
          icon: github
          href: https://github.com/OO-UU/workbook_IIQ2013/blob/main/e_prop/00_bernoulli/jupyter/e00_1.ipynb

execute: 
  echo: true

jupyter: python3
---

## Enunciado

Un estanque cilíndrico de diámetro $d_e=10\hspace{1mm}(m)$ se llena de agua hasta alcanzar los $25\hspace{1mm}(m)$ de altura. En su parte inferior se encuentra una tubería conectada a una válvula. Al abrir la válvula, el agua fluye por la tubería y el estanque se vacía. La tubería tiene un área transversal circular y con diámetro $d_t=13\hspace{1mm}(cm)$. Ignore las pérdidas de carga por fricción y singularidades. Además, suponga que la presión en la tubería es igual a la presión de la superficie del fluido en el estanque.

Calcule lo siguiente:

1. El caudal que sale por la tubería al momento de abrir la válvula.
2. El tiempo que se demora el estanque en vaciarse por completo.

## Solución

<button class="btn btn-success" data-bs-toggle="collapse" href="#e00_1-sol" aria-expanded="false">Mostrar solución</button>

::: {#e00_1-sol .collapse .multi-collapse}

```{python}
#Paquetes utilizados
import handcalcs.render
handcalcs.set_option("latex_block_start", "$$")
handcalcs.set_option("latex_block_end", "$$")
from math import sqrt, pi
```

### Inciso 1

Tenemos que la `ecuación de Bernoulli`:

$$
\frac{p_A}{g\rho} + H_A + \frac{u_A^2}{2g} = \frac{p_B}{g\rho} + H_B + \frac{u_B^2}{2g}
$$

Aplicada al caso descrito

$$
H_A = \frac{u_B^2}{2g}
$$

Y luego despejando para la velocidad en el punto inferior (B), nos queda como:

$$
u_B = \sqrt{2gH_A}
$$ {#eq-1}

Finalmente resolviendo:

```{python}
#| tags: []
%%render long
H_A = 25 #m
g = 9.8 #m/s2
u_B = sqrt(2*g*H_A) #m/s
```

Luego, el caudal será

$$
Q = u_BA
$$ {#eq-2}

```{python}
%%render long
d_t = 0.13 #m 
A = pi*(d_t/2)**2 #m2
Q = u_B*A #m3/s
```

### Inciso 2

El caudal también puede ser escrito como:

$$
Q = - \frac{dV}{dt}
$$

Ya que el diámetro del estanque se mantiene constante

$$
Q = -\pi\left(\frac{d_e}{2}\right)^2\frac{dH_A}{dt}
$$

Al reemplazar la ecuación [-@eq-1] en [-@eq-2] e igualando,

$$
\sqrt{2gH_A}\left(\pi\left(\frac{d_t}{2}\right)^2\right) = -\pi\left(\frac{d_e}{2}\right)^2\frac{dH_A}{dt}
$$

Reordenando los términos,

$$
-H_A^{-\frac{1}{2}}dH_A = \sqrt{2g}\left(\frac{d_t}{d_e}\right)^2dt
$$

Inicialmente la altura del líquido es de $25\hspace{1mm}(m)$ hasta que en el tiempo final se vacía.

$$
-\int_{25}^{0}H_A^{-\frac{1}{2}}dH_A = \sqrt{2g}\left(\frac{d_t}{d_e}\right)^2 \int_0^{t_T}dt
$$

Finalmente,

$$
t_T = 2\sqrt{\frac{25}{2g}}\left(\frac{d_e}{d_t}\right)^2
$$

```{python}
%%render long
d_e = 10 #m
t_T = 2*sqrt(25/2*g)*(d_e/d_t)**2 #s
## O
t = t_T/3600 #h
```
:::