---
title: 'Ejercicio clase 12'
format:
    html: 
      code-copy: true
      code-fold: false
      code-links: 
        - text: "Descargar Jupyter (.ipynb)"
          icon: github
          href: https://github.com/OO-UU/workbook_IIQ2013/blob/main/e_clase/jupyter/IIQ2013_C12.ipynb

execute: 
  echo: true

jupyter: python3
---

Se usa un intercambiador de calor de tubos y carcasa (**ICTC**) tipo 1-2 para enfriar $20~\text{ton/h}$ de agua (flujo por el lado de la carcasa) de $81$ a $33\text{°C}$ usando $120~\text{ton/h}$ de agua de enfriamiento a $17~\text{°C}$ (flujo por el lado de los tubos). El ICTC dispone de $Nt = 60$ tubos de $1~\text{in}$ de diámetro nominal ($D_0 = 2.54~\text{cm}$; $D_i = 2.21~\text{cm}$) y $L = 2.44~\text{m}$ de largo ordenados según un arreglo cuadrado de $1.25~\text{in}$ de paso dentro de una carcasa de $D_c = 31.9~\text{cm}$ de diámetro.

Paquetes utilizados:

```{python}
import numpy as np
import handcalcs.render
handcalcs.set_option("latex_block_start", "$$")
handcalcs.set_option("latex_block_end", "$$")
import forallpeople as si
from math import pi, log
```

```{python}
si.environment('default', top_level=True)
```

## Pregunta 1

El área de transferencia de calor ($A$) del equipo es la siguiente:

(a) $A \leq 10~\text{m}^2$\
(b) $10 < A \leq 11~\text{m}^2$\
(c) $11 < A \leq 12~\text{m}^2$\
(d)) $A > 12~\text{m}^2$

<button class="btn btn-success" data-bs-toggle="collapse" href="#ec_12-1-sol" aria-expanded="false">Mostrar solución</button>

::: {#ec_12-1-sol .collapse .multi-collapse}

Primero anotamos todos los datos disponibles

```{python}
%%render params
F_h = 20 * 1e3 / 3600 * kg / s
T_hi = 81 * K
T_ho = 33 * K

F_c = 120 * 1e3 / 3600 * kg / s
T_ci = 17 * K

N_t = 60 
d_o = 0.0254 * m
d_i = 0.0221 * m

L = 2.44 * m
```

El área de intercambio de calor puede calcularse directamente a partir de la geometría del tubo y del número de tubos del arreglo

$$ A = N_t \pi d_o L $$

```{python}
%%render
A = N_t * pi * d_o * L
```

Por lo tanto, la alternativa correcta es **c**.

:::

## Pregunta 2

La diferencia de temperatura relevante para el diseño del ICTC ($\Delta T$) es la siguiente:

(a) $\Delta T \leq 29~\text{°C}$\
(b) $29 <\Delta T \leq 30~\text{°C}$\
(c) $30 < \Delta T \leq 31~\text{°C}$\
(d) $\Delta T > 31~\text{°C}$

<button class="btn btn-success" data-bs-toggle="collapse" href="#ec_12-2-sol" aria-expanded="false">Mostrar solución</button>

::: {#ec_12-2-sol .collapse .multi-collapse}

Ahora tenemos que calcular la diferencia de temperatura relevante para el diseño del intercambiador de calor de tubo y carcasa. Para ello, calculamos los factores $Z$ y $F_h$ con el propósito de estimar el factor de corrección $F_T$.

```{python}
%%render
Z = F_c/F_h
```

```{python}
%%render
T_co = (T_hi - T_ho)/Z + T_ci
```

```{python}
#| scrolled: true
%%render
eta_H = (T_co - T_ci) / (T_hi - T_ci)
```

Utilizando la fórmula para el $F_T$ de un ICTC 1-2,

```{python}
def Ft_12(Z, eta):
    num = np.sqrt(Z**2 + 1) * np.log( (1-eta) / (1-eta*Z))
    den = (Z-1) * np.log ( (2-eta*(Z+1 - np.sqrt(Z**2+1)))
                          / (2-eta*(Z+1 + np.sqrt(Z**2+1))))
    F_t = num/den
    return F_t
```

```{python}
F_t = Ft_12(Z, eta_H)
```

```{python}
%%render
F_t = F_t
```

Ahora calculamos $\Delta T_{ml}$

```{python}
%%render
dT_h = T_hi - T_co
dT_c = T_ho - T_ci
dT_lm = (dT_h-dT_c)/log(dT_h/dT_c)

## Tal que la diferencia de temperaturas relevantes es:
dT = F_t * dT_lm
```

Por lo tanto, la alternativa correcta es la **b**.

:::

## Pregunta 3

Si la carcasa tiene $N_B = 30$ deflectores segmentales igualmente espaciados, el coeficiente de transferencia de calor por convección para el agua caliente que circula por el lado de la carcasa ($h_c$) es el siguiente:

(a) $h_c < 3750~\text{W/m}^2\cdot\text{K}$\
(b) $3750 \leq h_c < 5000~\text{W/m}^2\cdot\text{K}$\
(c) $5000 \leq h_c < 7500~\text{W/m}^2\cdot\text{K}$\
(d) $h_c \geq 7500~\text{W/m}^2\cdot\text{K}$

Considere los siguiente valores para las propiedades termofísicas del agua a $57~\text{°C}$: $\rho = 984~\text{kg/m}^3$; $c_p = 4184~\text{J/kg}\cdot\text{K}$, $\mu = 0.489\times10^{−3}~\text{Pa}\cdot\text{s}$; $k = 0.650~\text{W/m}\cdot\text{K}$; y $Pr = 3.148$.

<button class="btn btn-success" data-bs-toggle="collapse" href="#ec_12-3-sol" aria-expanded="false">Mostrar solución</button>

::: {#ec_12-3-sol .collapse .multi-collapse}

Parámetros geométricos y físicos,

```{python}
%%render params
N_b = 30 # número de deflectores
B = L/N_b # espaciamiento entre deflectores
mu = 0.489e-3 * Pa * s
c_p = 4184 * J / kg / K
k = 0.65 * W / m / K
Pr = 3.148
```

Cálculo del número de Reynolds

```{python}
%%render
S_T = 1.25 * 0.0254 * m # Paso del arreglo
D_e = (4*S_T**2- np.pi * d_o**2)/(np.pi * d_o) # Diámetro equivalente
# Shell diameter
D_c = 0.319 * m # Diámetro de la carcasa
a_c = D_c * B * (S_T-d_o)/S_T # Área libre de flujo
G = F_h/a_c
# Reynolds number calculation
Re = G * D_e / mu
```

Cálculos de transferencia de calor. Asumiremos que $\mu_s/\mu \sim 1$

```{python}
%%render
j_h = 0.36 * Re**0.55 
Nusselt = j_h * Pr**(1/3)
h_c = Nusselt * k / D_e
```

:::

## Pregunta 4

Si el coeficiente de transferencia de calor por convección para el agua fría que circula por el lado de los tubos es $h_t = 10000~\text{W/m}^2\cdot\text{K}$, la resistencia de ensuciamiento de diseño ($R_d$) es la siguiente:

(a) $R_d < 10^{−5}~\text{m}^2\cdot{K/W}$\
(b) $10^{−5} \leq R_d < 4\times10^{−5}~\text{m}^2\cdot{K/W}$\
(c) $4\times10^{−5} \leq R_d < 10^{−4}~\text{m}^2\cdot{K/W}$\
(d) $R_d \geq 10^{−4}~\text{m}^2\cdot{K/W}$

<button class="btn btn-success" data-bs-toggle="collapse" href="#ec_12-4-sol" aria-expanded="false">Mostrar solución</button>

::: {#ec_12-4-sol .collapse .multi-collapse}

Desde la ecuación de diseño.

$$ q = UA F_t \Delta T_{ml}$$

```{python}
%%render sci_not
h_t = 10000 * W / m**2 / K
q = F_h * c_p * (T_hi - T_ho)
U_T = q/(A*dT)
U = (d_o/(d_i*h_t) + 1/h_c)**(-1)
R_f = 1/U_T - (d_o/(d_i*h_t) + 1/h_c)
```

$R_f = 1.0023 \times 10 ^{-5} m^2  K W^{-1}$

Por lo tanto la alternativa correcta es **b**.

:::