---
title: 'Ejercicio clase 2'
format:
    html: 
      code-copy: true
      code-fold: false
      code-links: 
        - text: "Descargar Jupyter (.ipynb)"
          icon: github
          href: https://github.com/OO-UU/workbook_IIQ2013/blob/main/e_clase/jupyter/IIQ2013_C3.ipynb

execute: 
  echo: true

jupyter: python3
---


En primer lugar se deben cargar las librerias que vamos a utilizar

```{python}
import numpy as np
```

## Pregunta 1

La pérdida de carga ($\Delta p/L$) al transportar $Q$ = 100 L/s de agua por una tubería horizontal de acero comercial de 10 in de diámetro nominal (D= 254,5 mm) es la siguiente:
       

(a) $\Delta p/L >$ 0.13 atm/100 m

(b) 0.12 $< \Delta p/L \leq$ 0.13 atm/100 m

(c) 0.11 $< \Delta p/L \leq$ 0.12 atm/100 m

(d) $\Delta p/L \leq$ 0.11 atm/100 m


Considere las propiedades físicas del agua a 20 °C [$\rho$= 1000 kg/m$^3$, $\mu$= 0.001 Pa s].

<button class="btn btn-success" data-bs-toggle="collapse" href="#ec_2-1-sol" aria-expanded="false">Mostrar solución</button>

::: {#ec_2-1-sol .collapse .multi-collapse}

Comenzamos recordando el ejercicio de la clase anterior ...

```{python}
# 1
d = 254.5e-3
Q = 0.1 # m^3/s
V = Q/(np.pi*d**2/4) # Calculamos la velocidad 
rho = 1000
mu = 0.001
Re = rho*V*d/mu
eps = 0.046*1e-3
def f_Nevers(eps, D, Re):
    return 0.001375 * (1 + (2e4 * eps/D + 1e6/Re)**(1/3))

f = f_Nevers(eps, d, Re)

L = 100 # m
phi = 4 * f * (L/d) * (V**2/2)
print(f"La perdida de carga por unidad de largo es {1000 * phi/L} Pa/m")

```

Realizando el cambio de unidades

```{python}
print(f"La perdida de carga por unidad de largo es {100000 * phi/L*9.86923e-6} atm/100 m")
```

Por lo tanto la alternativa correcta es la **c**.

:::

## Pregunta 2

La pérdida de carga en un tramo de 100 metros de la tubería de (1) que inclute una válvula de compuerta abierta en un 75\%, estimada usando el valor tabulado de coeficiente de pérdida de energía para la válvula, es la siguiente:

(a) $\Delta p >$ 0.13 atm 

(b) 0.12 $< \Delta p \leq$ 0.13 atm 

(c) 0.11 $< \Delta p \leq$ 0.12 atm 

(d)  $\Delta p \leq$ 0.11 atm 


<button class="btn btn-success" data-bs-toggle="collapse" href="#ec_2-2-sol" aria-expanded="false">Mostrar solución</button>

::: {#ec_2-2-sol .collapse .multi-collapse}

Necesitamos sumar el coeficiente de fricción con el coeficiente de fricción por singularidad. Para una válvula de compuerta abierta en un 75% utilizamos un valor de K = 1

```{python}
K = 1
f = f_Nevers(eps, d, Re)
L = 100 # m
phi = (4 * f * (L/d) + K) * (V**2/2)
print(f"La perdida de carga {1000 * phi*9.86923e-6} atm")

```

Por lo tanto la alternativa correcta es la **a**.

:::

## Pregunta 3

El valor de la pérdida de carga (2), pero evaluado considerando que el largo equivalente ($L_e$/D) de una válvula de compuerta abierta en un 75\% es 40, es el siguiente:

(a) $\Delta p >$ 0.13 atm 

(b) 0.12 $< \Delta p \leq$ 0.13 atm 

(c) 0.11 $< \Delta p \leq$ 0.12 atm 

(d)  $\Delta p \leq$ 0.11 atm 

<button class="btn btn-success" data-bs-toggle="collapse" href="#ec_2-3-sol" aria-expanded="false">Mostrar solución</button>

::: {#ec_2-3-sol .collapse .multi-collapse}

Ocupando la aproximación del largo equivalente

```{python}
K = 1
f = f_Nevers(eps, d, Re)
L = 100 # m
phi = (4 * f * (L/d + 40) ) * (V**2/2)
print(f"La perdida de carga {1000 * phi*9.86923e-6} atm")
```

Por lo tanto la alternativa correcta es la **b**.

:::