---
title: 'Ejercicio clase 6'
format:
    html: 
      code-copy: true
      code-fold: false
      code-links: 
        - text: "Descargar Jupyter (.ipynb)"
          icon: github
          href: https://github.com/OO-UU/workbook_IIQ2013/blob/main/e_clase/jupyter/IIQ2013_C6.ipynb

execute: 
  echo: true

jupyter: python3
---



Un compañero desea emprender creando un innovador SPA que utiliza un aceite esencial especial con harina disuelta como exfoliante. Esta suspensión es un fluido newtoniano con una viscosidad de $8000\hspace{1mm}cP$ y una densidad $\rho=880\hspace{1mm}(kg/m^3)$. 

En primer lugar se deben cargar las librerias que vamos a utilizar

```{python}
import numpy as np
from numpy import sqrt, pi
import handcalcs.render
from handcalcs import handcalc
```

## Pregunta 1

Su compañero encontró que es mucho más barato preparar la suspensión en lugar de comprarla. Para ello, se encuentra seleccionando estanques y agitadores. Para un tanque de $3\hspace{1mm}m^3$, ¿qué agitador le recomendaría?

(a) Turbina

(b) Hélice

(c) Ancla

(d) Paleta

::: {#ec_2-1-sol .collapse .multi-collapse}

```{figure} ./images/img_EC-7.png
---
name: figura-EC7
scale: 60%
align: center
---

Gráfico de selección.
```


Del gráfico:
Por lo tanto, la alternativa correcta es la **a**.

:::

## Pregunta 2

Si la altura del estanque cilíndrico es de $2\hspace{1mm}(m)$, la razón entre el diámetro del agitador y el diámetro del estanque es $S1 = D/T = 0.2$, y el número del flujo del agitador es $NQ = 0.87$, ¿Cuál es el caudal volumétrico descargado del borde del agitador operando a $120\hspace{1mm}RPM$?

(a) Q $<$ 0.15 m$^3$/s

(b) 0.15 m$^3$/s $\leq$ Q $<$ 0.20 m$^3$/s

(c) 0.12 m$^3$/s $\leq$ Q $<$ 0.25 m$^3$/s

(d) Q $\geq$ 0.25 m$^3$/s

::: {#ec_2-1-sol .collapse .multi-collapse}


```{python}
%%render long
H = 2 #m
V = 3 #m$^3$
S_1 = 0.2
D_t = sqrt(4*V/(pi*H)) #m
D_a = D_t*S_1 #m
NQ = 0.87
N = 120 #RPM
Q = NQ*(N/60)*D_a**3 #m$^3$/s
```

La alternativa correcta es la **a**.

:::

## Pregunta 3

El fabricante del agitador reporta que para un diámetro del agitador de $0.3\hspace{1mm}m$, la potencia requerida para $180\hspace{1mm}RPM$ es de $5.5 \hspace{1mm}kW$. ¿Qué potencia requiere el agitador diseñado en la pregunta anterior?

(a) P $<$ 0.15 kW

(b) 0.5 kW $\leq$ P $<$ 1.5 kW

(c) 1.5 kW $\leq$ P $<$ 2.5 kW

(d) P $\geq$ 2.5 kW

::: {#ec_2-1-sol .collapse .multi-collapse}

Se debe cumplir que el número de potencia es equivalente.

$$
N_{p,1} = N_{p,2} \Rightarrow \frac{P_1}{\rho_1N_1^3D_{a,1}^5} = \frac{P_2}{\rho_2N_2^3D_{a,2}^5}
$$

```{python}
%%render long
N_1 = 180 #RPM
N_2 = N #RPM
P_1 = 5.5 #kW
D_a1 = 0.3 #m
D_a2 = D_a #m
P_2 = P_1*((N_2/60)**3*D_a2**5)/((N_1/60)**3*D_a1**5) #kW
```

La alternativa correcta es la **b**.

:::


