---
title: 'Ejercicio clase 8'
format:
    html: 
      code-copy: true
      code-fold: false
      code-links: 
        - text: "Descargar Jupyter (.ipynb)"
          icon: github
          href: https://github.com/OO-UU/workbook_IIQ2013/blob/main/e_clase/jupyter/IIQ2013_C8.ipynb

execute: 
  echo: true

jupyter: python3
---



Se efectúa un experimento en un estanque de laboratorio con configuración estándar de $10 \mathrm{~L}$ de capacidad $(H / D_T=1)$ y equipado con una turbina de seis palas. Experimentalmente se determina que el tiempo de mezclado para alcanzar una uniformidad superior a $99.99 \%$ en una solución $\left[\rho=1000 \mathrm{~kg} / \mathrm{m}^3, \mu=60 \mathrm{~cp}\right]$ es aproximadamente $t_{\mathrm{m}}=1 \mathrm{~min}$ al operar a $500 \mathrm{~rpm}$. Interesa usar dichos datos para dimensionar un estanque industrial para mezclar $100 \mathrm{~m}^3$ de solución.

En primer lugar se deben cargar las librerias que vamos a utilizar

```{python}
import numpy as np
from numpy import sqrt, pi
import handcalcs.render
from handcalcs import handcalc
handcalcs.set_option("latex_block_start", "$$")
handcalcs.set_option("latex_block_end", "$$")
```

## Problema 1

Si para una configuración estándar de estanque agitado con turbina $D_T / D_a=4$, entonces el diámetro de agitador industrial $(D_a)$ es el siguiente:

(a) $D>120 \mathrm{~cm}$

(b) $80<D \leq 120 \mathrm{~cm}$

(c) $40<D \leq 80 \mathrm{~cm}$

(d) $D \leq 40 \mathrm{~cm}$

<button class="btn btn-success" data-bs-toggle="collapse" href="#ec_8-1-sol" aria-expanded="false">Mostrar solución</button>

::: {#ec_8-1-sol .collapse .multi-collapse}

Sabemos el volumen, luego despejamos para $D_t$ del agitador de laboratorio.

$$
D_t = \sqrt[3]{\frac{4V}{\pi}}
$$

```{python}
%%render long
#Para volumen laboratorio
V = 0.01 #m$^3$
S_1 = 1/4
D_Tm = ((4*V)/pi)**(1/3) #m
D_am = D_Tm*S_1 #m
```

luego para el agitador de industrial.

```{python}
%%render long
#Para volumen laboratorio
V = 100 #m$^3$
S_1 = 1/4
D_Tp = ((4*V)/pi)**(1/3) #m
D_ap = D_Tp*S_1 #m
```

La alternativa correcta es la **a**.

:::

## Problema 2

Si la calidad del mezclado depende principalmente de la velocidad de punta del agitador, la velocidad a la que debe operar el agitador industrial $(N)$ es la siguiente:

(a) $N>270 \mathrm{rpm}$

(b) $90<N \leq 270 \mathrm{rpm}$

(c) $30<N \leq 90 \mathrm{rpm}$

(d) $N \leq 30 \mathrm{rpm}$

<button class="btn btn-success" data-bs-toggle="collapse" href="#ec_8-2-sol" aria-expanded="false">Mostrar solución</button>

::: {#ec_8-2-sol .collapse .multi-collapse}

Utilizando el criterio de ND constante,

$$
N_m D_{d, m}=N_p D_{a, p} \Rightarrow N_p=N_m \frac{D_{T, m}}{D_{T, p}}
$$ 

```{python}
%%render long
Nm = 500 #RPM
Np = Nm*D_Tm/D_Tp #RPM
```

La alternativa correcta es la **d**.

:::

## Problema 3

 El régimen de flujo en el estanque industrial es el siguiente:

(a) Laminar

(b) De transición de laminar a turbulento

(c) Turbulento

(d) No existe suficiente información para determinar el régimen de flujo

<button class="btn btn-success" data-bs-toggle="collapse" href="#ec_8-3-sol" aria-expanded="false">Mostrar solución</button>

::: {#ec_8-3-sol .collapse .multi-collapse}

Para esto calculamos el número de Reynolds

$$
Re=\frac{\rho_p N_p D_{a, p}^2}{\mu_p}
$$

```{python}
%%render long
rho = 1000 #kg/m$^3$
mu = 0.06 #Pa$\cdot$s
Re = (rho*(Np/60)*D_ap**2)/mu
```

La alternativa correcta es la **c**, régimen turbulento.

:::

## Problema 4

Si en las pruebas de laboratorio se determina que $K_{\mathrm{L}}=65$ y $K_{\mathrm{T}}=5.75$, entonces el consumo de potencia del agitador industrial $(P)$ es aproximadamente el siguiente:

(a) $P>25 \mathrm{~kW}$

(b) $5<P \leq 25 \mathrm{~kW}$

(c) $1<P \leq 5 \mathrm{~kW}$

(d) $P \leq 1 \mathrm{~kW}$

<button class="btn btn-success" data-bs-toggle="collapse" href="#ec_8-4-sol" aria-expanded="false">Mostrar solución</button>

::: {#ec_8-4-sol .collapse .multi-collapse}

```{python}
%%render long
K_T = 5.75
P = K_T*rho*(Np/60)**3*D_ap**5/1000 #kW
```

La alternativa correcta es la **c**.

:::