---
title: 'Ejercicio clase 15'
format:
    html: 
      code-copy: true
      code-fold: false
      code-links: 
        - text: "Descargar Jupyter (.ipynb)"
          icon: github
          href: https://github.com/OO-UU/workbook_IIQ2013/blob/main/e_clase/jupyter/IIQ2013_C15.ipynb

execute: 
  echo: true

jupyter: python3
---

Se usa un intercambiador de calor de tubos y carcasa (ICTC) tipo 1-2n para enfriar $F_h = 20~\text{ton/h}$ de agua (flujo por lado de carcasa) a $T_{h,i} = 81~\text{°C}$ con $F_c = 120~\text{ton/h}$ de agua de enfriamiento a $T_{c,i} = 17~\text{°C}$ (flujo por el lado de los tubos). El ICTC dispone de $N_t = 60$ tubos de $1~\text{in}$ de diámetro nominal ($D_o = 2.54~\text{cm}$; $D_i = 2.21 ~\text{cm}$) y $L = 2.44~\text{m}$ de largo ($A = 11.7~\text{m}^2$) ordenados según un arreglo cuadrado de $P_T = 1.25~\text{in}$ de paso. La carcasa tiene $D_c =31.9~\text{cm}$ de diámetro, y está equipada con $N_B = 30$ deflectores segmentales igualmente espaciados.

```{python}
import handcalcs.render
handcalcs.set_option("latex_block_start", "$$")
handcalcs.set_option("latex_block_end", "$$")
import forallpeople
import numpy as np
import forallpeople as si
```

```{python}
si.environment('default', top_level=True)
```

## Pregunta 1

El coeficiente de transferencia de calor por convección para el agua caliente que circula por el lado de la carcasa ($h_c$) es aproximadamente el siguiente:

(a) $h_c$ $<$ 3750 $\text{W/m}^2\cdot\text{K}$\
(b) 3750 $\leq$ $h_c$ $<$ 5000 $\text{W/m}^2\cdot\text{K}$\
(c) 5000 $\leq$ $h_c$ $<$ 7500 $\text{W/m}^2\cdot\text{K}$\
(d) $h_c$ $\geq$ 7500 $\text{W/m}^2\cdot\text{K}$

Las propiedades termofísicas para el agua por el lado de la carcasa evaluado a la temperatura promedio son: $\mu_c = 0.489~\text{cP}$, $Pr_c = 3.15$, $k_c = 0.65~\text{W/m}\cdot\text{K}$.

<button class="btn btn-success" data-bs-toggle="collapse" href="#ec_15-1-sol" aria-expanded="false">Mostrar solución</button>

::: {#ec_15-1-sol .collapse .multi-collapse}

```{python}
%%render
L = 2.44 * m
D_o = 0.0254 * m
N_b = 30 # Número de deflectores
D_c = 0.319*  m # Diámetro de la carcasa
P_t = 1.25 * 0.0254* m
B = L/(N_b+1) # espaciamiento entre deflectores
a_c = D_c * B *(P_t-D_o)/P_t
```

```{python}
%%render
F_h = 20*1e3/3600 * kg / s
mu = 4.89e-4 * Pa *s
G_c = F_h/a_c
pi = np.pi
D_e = (4*P_t**2 - pi*D_o**2)/(pi*D_o)
Re_c = G_c * D_e / mu
```

Por lo tanto el flujo por el lado de la carcasa es turbulento.

```{python}
%%render
j_h = 0.36 * Re_c**0.55
Pr = 3.15
Nusselt_c = Pr**(1/3) * j_h
k = 0.650 * W / m / K
h_c = Nusselt_c*k/D_e
```

Por lo tanto la alternativa correcta es **c**

:::

## Pregunta 2:

El coeficiente de transferencia de calor por convección para el agua de enfriamiento que circula por el lado de los tubos ($h_t$) es aproximadamente el siguiente:

(a) $h_t$ $<$ 7500 $\text{W/m}^2\cdot\text{K}$\
(b) 7500 $\leq$ $h_t$ $<$ 9000 $\text{W/m}^2\cdot\text{K}$\
(c) 9000 $\leq$ $h_t$ $<$ 12000 $\text{W/m}^2\cdot\text{K}$\
(d) $h_t$ $\geq$ 12000 $\text{W/m}^2\cdot\text{K}$

Las propiedades termofísicas para el agua por el lado del tubo evaluado a la temperatura promedio son: $\mu_t = 0.959~\text{cP}$, $Pr_t = 6.62$, $k_t = 0.0.606~\text{W/m}\cdot\text{K}$.

<button class="btn btn-success" data-bs-toggle="collapse" href="#ec_15-2-sol" aria-expanded="false">Mostrar solución</button>

::: {#ec_15-2-sol .collapse .multi-collapse}

```{python}
%%render
N = 60 # Número de tubos
n = 2 # Número de pasadas
D_i = 0.0221 * m
a_t = pi * D_i**2 / 4 * (N/n)
F_c = 120*1e3/3600 * kg / s
G_t = F_c/a_t
```

Con el flux másico por el lado de los tubos, podemos calcular el número de Reynolds en el lado de los tubos.

```{python}
%%render
mu_t = 9.59e-4 * Pa * s
Re_t = (G_t * D_i) / mu_t
```

Por lo tanto el flujo es turbulento. Asumiendo paredes lisas, podemos utilizar la ecuación de Dittus Boelman.

```{python}
%%render 
n = 0.4 #(Para calentamiento)
Pr_t = 6.62
Nusselt_t = 0.023 * Re_t ** 0.8 * Pr_t ** 0.4
k_t = 0.606 * W / m / K # (Conductividad térmica por el lado de los tubos)
h_t = Nusselt_t * k_t / D_i
```

Por lo tanto la alternativa correcta es **c**.

:::

## Pregunta 3

Usando el método $\epsilon-\text{NTU}$, se puede estimar que, en este ICTC, el agua caliente se enfría hasta aproximadamente la siguiente temperatura:

(a) $T_{h,o}$ $<$ 30 °C\
(b) 30 $\leq$ $T_{h,o}$ $<$ 40 °C\
(c) 40 $\leq$ $T_{h,o}$ $<$ 50 °C\
(d) $T_{h,o}$ $\geq$ 50 °C

<button class="btn btn-success" data-bs-toggle="collapse" href="#ec_15-3-sol" aria-expanded="false">Mostrar solución</button>

::: {#ec_15-3-sol .collapse .multi-collapse}

Primero, calculamos las NTU basadas en el fluido con menor capacidad calórica. En este caso, es el fluido por la carcasa. 

```{python}
%%render
c_pc = 4184 * J / kg / K
c_ph = 4181 * J / kg / K
C_c = F_c*c_pc
C_h = F_h*c_ph

U =  (1/h_c + 1/h_t * D_o/D_i)**-1
A = 11.7 * m**2
NTU = (U*A)/(C_h)
```

Calcularemos la efectividad del ICTC de manera analítica

```{python}
from math import sqrt, exp
```

```{python}
%%render
C_r = C_h/C_c
epsilon = 2 / (1 + C_r + sqrt(1+C_r**2) * (1+exp(-NTU*sqrt(1+C_r**2)))/(1-exp(-NTU*sqrt(1+C_r**2))))
```

Con la eficiencia, podemos calcular la temperatura de salida del fluido por la carcasa

```{python}
%%render
T_hi = 81 * C
T_ci = 17 * C
T_ho = T_hi - (T_hi - T_ci)*epsilon
```

:::