---
title: 'Ejercicio clase 14'
format:
    html: 
      code-copy: true
      code-fold: false
      code-links: 
        - text: "Descargar Jupyter (.ipynb)"
          icon: github
          href: https://github.com/OO-UU/workbook_IIQ2013/blob/main/e_clase/jupyter/IIQ2013_C14.ipynb

execute: 
  echo: true

jupyter: python3
---

Interesa evaluar el tiempo que demora calentar $V = 10~\text{m}^3$ de glicerina de $T_i = 25~\text{°C}$ a $T_f = 35~\text{°C}$ en un estanque agitado de configuración estándar ($D_a/D_t = 1/3$, $H/D_t = 1$) equipado con un impulsor de ancla que opera a $N = 32~\text{RPM}$, y una camisa con deflectores
(ancho, $w = 10~\text{cm}$) por la que circulan $F = 12000~\text{kg/h}$ de vapor de agua a $T_{hi} = 100~\text{°C}$.

Librerias a utilizar

```{python}
import handcalcs.render
handcalcs.set_option("latex_block_start", "$$")
handcalcs.set_option("latex_block_end", "$$")
import forallpeople
import numpy as np
import forallpeople as si
si.environment('default', top_level=True)
```

## Pregunta 1

Estime el coeficiente de transferencia de calor para glicerina en el estanque (considere los siguientes valores de las propiedades físicas de la glicerina a $30~\text{°C}$: $r = 1260~\text{kg/m}^3$; $\mu = 0.656~\text{Pa}\cdot\text{s}$; $k = 0.286~\text{W/m}\cdot\text{K}$; y $Pr = 5590$) 

(a) $h_o$ $>$ 60 $\text{W/m}\cdot\text{K}$\
(b) 50 $\leq$  $h_o$ $<$ 60 $\text{W/m}\cdot\text{K}$\
(c) 40 $\leq$  $h_o$ $<$ 50 $\text{W/m}\cdot\text{K}$\
(d) $h_o$ $<$ 40 $\text{W/m}\cdot\text{K}$

<button class="btn btn-success" data-bs-toggle="collapse" href="#ec_14-1-sol" aria-expanded="false">Mostrar solución</button>

::: {#ec_14-1-sol .collapse .multi-collapse}

```{python}
%%render params
rho = 1260 * kg/m**3
N = 32/60 * 1/s
D_a = 0.778 * m
mu = 0.656 * Pa * s
```

```{python}
%%render long
Re = rho*N*D_a**2/mu
```

Ahora calculamos el diámetro del estanque y del agitador

```{python}
#| scrolled: true
%%render long
V_t = 10 * m **3
pi = np.pi
D_t = (4*V_t/pi)** (1/3)
D_a = D_t/3
```

Ahora calculamos el coeficiente de convección por el lado del fluido agitado

```{python}
%%render long
Pr = 5590
Nusselt_t = 0.36 * (Re)**0.67 * Pr**(0.33)
k = 0.286 * W / m / K
h_o = Nusselt_t*k/D_t
```

Por lo tanto, la alternativa correcta es la **b**.

:::

## Pregunta 2

En base al diámetro equivalente para el fluido que circula por la chaqueta, estime el coeficiente de transferencia de calor por convección para el vapor de agua de calefacción. Asuma que el vapor de agua no cambia de fase y se mantiene a temperatura constante. Considere $\rho = 0.59~\text{kg/m}^3$, $\mu = 0.01~\text{cP}$, $k = 0.025~\text{W/m}\cdot\text{K}$, $Pr = 1$.

(a) $h_c$ $\geq$ 150 $\text{W/m}\cdot\text{K}$\
(b) 100 $\leq$ $h_c$ $<$ 150 $\text{W/m}\cdot\text{K}$\
(c) 50 $\leq$ $h_c$ $<$ 100 $\text{W/m}\cdot\text{K}$\
(d) $h_c$ $<$ 50 $\text{W/m}\cdot\text{K}$

*Hint: Recuerde la correlación de Sieder-Tate y el diámetro equivalente térmico.*

<button class="btn btn-success" data-bs-toggle="collapse" href="#ec_14-2-sol" aria-expanded="false">Mostrar solución</button>

::: {#ec_14-2-sol .collapse .multi-collapse}

```{python}
%%render long
D_ci = D_t
D_ce = D_t + 0.1*m
D_et = (D_ce**2 - D_ci**2)/D_ci
Z = D_t
a_c = Z*(D_ce-D_ci)
```

Ahora calculamos la velocidad del fluido en la chaqueta,

```{python}
si.environment('default', top_level=True)
```

```{python}
%%render long 5
rho_v = 0.59 * kg / m**3 # Densidad del fluido de servicio
mu_v = 0.01*1e-3*Pa*s
k_v = 0.025 *  W / m / K
F = 12000/3600 * kg / s
V = F/(rho_v*a_c)
Re = rho_v * V * D_et / mu_v
Nusselt_chaqueta = 0.027 * Re ** 0.8
h_c = Nusselt_chaqueta * k_v / (D_et)
```

Por lo tanto, la respuesta correcta es la **c**.

:::

## Pregunta 3

Estime en forma aproximada el tiempo de calentamiento. (Puede considerar que para glicerina a $30~\text{°C}$, $c_P = 2437~\text{J/kg}\cdot\text{K}$).

(a) $t_c$ $\geq$ 200 min \
(b) 150 $\leq$ $t_c$ $<$ 200 min \
(c) 100 $\leq$ $t_c$ $<$ 150 min \
(d) $t_c$ $<$ 100 min

<button class="btn btn-success" data-bs-toggle="collapse" href="#ec_14-3-sol" aria-expanded="false">Mostrar solución</button>

::: {#ec_14-3-sol .collapse .multi-collapse}

```{python}
%%render long
M = V_t * rho
c_p = 2437 * J/kg/K
U = (1/h_o + 1/h_c)**-1 # Coeficiente global de transferencia de calor
```

Asumiendo que la chaqueta comienza en el diámetro externo del tanque, el área de transferencia de calor viene dada por

```{python}
%%render long
A = pi * D_t * Z
```

La diferencia de temperatura media logarítmica asumiendo que el vapor condensa por el lado de la chaqueta es

```{python}
%%render short
T_i = 25 * Celsius
T_f = 35 * Celsius
T_s = 100 * Celsius
DeltaT_ml = ((T_s-T_i) - (T_s-T_f))/(np.log((T_s-T_i)/(T_s-T_f)))
```

Finalmente, el tiempo de calentamiento es

```{python}
%%render long
t_s = M*c_p / (U*A) * np.log((T_s-T_i)/(T_s-T_f))
```

Lo que es equivalente a 130.6 minutos. Por lo tanto, la respuesta correcta es la **c**.

:::
