---
title: 'Ejercicio 1: ICDT'
format:
    html: 
      code-copy: true
      code-fold: true
      code-links: 
        - text: "Descargar Jupyter (.ipynb)"
          icon: github
          href: https://github.com/OO-UU/workbook_IIQ2013/blob/main/e_prop/04_ICDT/jupyter/e04_1.ipynb

execute: 
  echo: true

jupyter: python3
tbl-cap-location: bottom
---



## Enunciado

Se desea enfriar un flujo de tolueno ($0.48~\text{kg/s}$) hasta alcanzar los $75~\text{°C}$. Para esto, se utiliza un flujo de agua ($0.55~\text{kg/s}$) a contracorrientes que pasa por el ánulo de un intercambiador de doble tubo. Al inicio de la operación, el agua se encuentra a $10~\text{°C}$ y termina saliendo del proceso a $20~\text{°C}$. El tubo es de acero ($k_p = 50.2~\text{W/m}\cdot\text{K}$) y considere que su diámetro interno del tubo es $D_i=15~\text{cm}$, que el diámetro externo del tubo es $D_{i,e}=15.5~\text{cm}$ y que el díametro interno del ánulo es $D_a= 25~\text{cm}$.

Para las condiciones descritas en el enunciado, las propiedades termofísicas del tolueno y el agua son las siguientes:

| Fluido  | $c_P~\text{(J/kg}\cdot\text{K)}$ | $\rho~\text{(kg/m}^3\text{)}$ | $\mu~\text{(Pa}\cdot\text{s)}$ | $k~\text{(W/m}\cdot\text{K)}$ |
|---------|-----------------------------------|-------------------------------|--------------------------------|-------------------------------|
| Tolueno | 1917.25                           | 802.355                       | 3.003$\times 10^{-4}$          | 0.11329                       |
| Agua    | 4181.95                           | 996.93                        | 8.994$\times 10^{-4}$          | 0.6062                        |

: Propiedades termofísicas del tolueno y el agua en función de su temperatura promedio. {.striped .hover}

Encuentre lo siguiente:

1. La temperatura de entrada del tolueno.
2. Los coeficientes de transferencia de calor para fluido que circula por el tubo y por el ánulo.
3. Si el coeficiente de transferencia global total ($U_T$) es $28.43~\text{W/m}^2\cdot\text{K}$, encuentre el factor de ensuciamiento.

## Solución

<button class="btn btn-success" data-bs-toggle="collapse" href="#e04_1-sol" aria-expanded="false">Mostrar solución</button>

::: {#e04_1-sol .collapse .multi-collapse}

```{python}
import handcalcs.render
from handcalcs import handcalc
handcalcs.set_option("latex_block_start", "$$")
handcalcs.set_option("latex_block_end", "$$")
from numpy import pi, log
```

### Inciso 1

Para encontrar la temperatura de entrada del tolueno, podemos igualar los valores de $q$:

$$
q = \dot{m}_hc_{P,h}(T_{h,e}-T_{h,s}) = \dot{m}_cc_{P,c}(T_{c,s}-T_{c,e})
$$

Para este ejercicio, el fluido caliente (tolueno) con subíndice $h$ pasa por el tubo, mientras que el fluido de enfriamiento (agua) con subíndice $c$ pasa por el ánulo. Del enunciado recuperamos todas las variables relevantes.

```{python}
%%render params sci_not
m_c = 0.55 #kg/s
T_ce = 10+273.15 #K
T_cs = 20+273.15 #K
mu_c = 8.994e-4 #Pa$\cdot$s
c_Pc = 4181.95 #J/kg$\cdot$K
k_c = 0.6062 #W/m$\cdot$K
m_h = 0.48 #kg/s
T_hs = 75+273.15 #K
mu_h = 3.003e-4 #Pa$\cdot$s
c_Ph = 1917.25 #J/kg$\cdot$K
k_h = 0.11329 #W/m$\cdot$K
```

```{python}
%%render long
q = m_c*c_Pc*(T_cs-T_ce) #J/s
T_he = q/(m_h*c_Ph)+T_hs #K
```

### Inciso 2

Para calcular los coeficientes de transferencia de calor vienen dados por el número de Nusselt.

$$
Nu_D = \frac{hD_{térmico}}{k}
$$

El cual puede ser despejado de distintas correlaciones dependiendo del tipo de fluido. Por lo que es recomendable empezar calculando el número de Reynolds para discriminar el tipo de flujo.

$$
Re_D = \frac{D_{térmico}\cdot\dot{m}}{A_t\cdot\mu}
$$

Por un lado, el diámetro térmico equivalente para el flujo que pasa por el tubo será equivalente al diámetro interno de la tubería. Por otro lado, el diámetro térmico equivalente para el flujo que pasa por el ánulo, será el siguiente:

$$
D_{térmico} = \frac{D_{a}^2-D_{i,e}^2}{D_{i,e}}
$$

Luego, podemos calcular los números de Prandtl y de Reynolds para ambos flujos.

```{python}
%%render params
D_i = 15/100 #m
D_ie = 15.5/100 #m
D_a = 25/100 #m
k_p = 50.2 #W/m$\cdot$K
Pr_h = (mu_h*c_Ph)/k_h
Pr_c = (mu_c*c_Pc)/k_c
```

```{python}
%%render long
Re_Dh = (D_i*m_h)/(pi*(D_i/2)**2*mu_h)
D_t = (D_a**2-D_ie**2)/D_ie #m
Re_Dc = (D_t*m_c)/(pi*((D_a-D_ie)/2)**2*mu_c)
```

Notamos que ambos flujos son turbulentos, y por lo tanto, se cosidera que la mejor ecuación para encontrar el número de Nusselt será la relación de Dittus-Boelter.

```{python}
%%render long
NuD_h = 0.023*Re_Dh**0.8*Pr_h**0.3
NuD_c = 0.023*Re_Dc**0.8*Pr_c**0.4
```

Con lo cual se puede despejar el coeficiente de transferencia de calor para ambos fluidos.

```{python}
%%render long
h_h = (NuD_h*k_h)/(D_i) #W/m$^2\cdot$K
h_c = (NuD_c*k_c)/(D_t) #W/m$^2\cdot$K
```

### Inciso 3

Primero, calculamos el coeficiente global de transferencia de calor para un intercambiador de doble tubo sin ensuciamiento.

```{python}
%%render long
U = (D_ie/(D_i*h_h) + D_ie/(2*k_p)*log(D_ie/D_i) + 1/h_c)**-1 #W/m$^2\cdot$K
```

Luego podemos despejar el factor de ensuciamiento.

$$
\frac{1}{U_T} = \frac{1}{U} + R_f
$$

```{python}
%%render long
U_T = 28.43 #W/m$^2\cdot$K
R_f = 1/U_T - 1/U #m$^2\cdot$K/W
```

Finalmente, obtenemos que el factor de ensuciamiento es de $R_f = 0.014~\text{m}^2\cdot\text{K/W}$.

:::