---
title: 'Ejercicio 2: Método NTU - ICTC'
format:
    html: 
      code-copy: true
      code-fold: true
      code-links: 
        - text: "Descargar Jupyter (.ipynb)"
          icon: github
          href: https://github.com/OO-UU/workbook_IIQ2013/blob/main/e_prop/06_ICTC/jupyter/e06_2.ipynb

execute: 
  echo: true

jupyter: python3
tbl-cap-location: bottom
---



## Enunciado

Usted es el encargado de diseño de la planta de energía más importante de Chile. Para la producción de energía se utiliza vapor sobrecalentado a $130~\text{°C}$, el cual se desea enfriar y consendar tal que salga del intercambiador como líquido saturado. Suponga que su condensador actua como un intercambiador de tubo y carcasa tipo 1-2n a contra-corriente con $27000~\text{tubos}$. Los tubos son de acero ($k = 53~\text{W/m}\cdot\text{K}$ , $\varepsilon = 0.046$) con $d_e=30~\text{mm}$ y $d_i=26~\text{mm}$ de diámetro externo e interno respectivamente. El vapor pasa por la carcasa y se condensa con un coeficiente de convección asociado de $h_o=11000~\text{W/m}^2\cdot\text{K}$. Se utiliza agua a $20~\text{°C}$ como refrigerante. El flujo de refrigerante por cada tubo individual es de $1~\text{kg/s}$, con el cual se consigue una tasa de transferencia de calor de $q=2\times10^{9}~\text{W}$.

Por un lado, las propiedades del vapor, sabe que el calor latente será $h_{fg}=2183~\text{kJ/kg}$ (considerando $T^{sat}=100~\text{°C}$) y el calor específico de gas será $c_{p,g}=2158~\text{J/kg}\cdot\text{K}$.

Por otro lado, las propiedades termofísicas del agua refrigerante, utilice la siguiente tabla.

| Fluido | $c_P~\text{(J/kg}\cdot\text{K)}$ | $\rho~\text{(kg/m}^3\text{)}$ | $\mu~\text{(Pa}\cdot\text{s)}$ | $k~\text{(W/m}\cdot\text{K)}$ | Pr   |
|--------|----------------------------------|-------------------------------|--------------------------------|-------------------------------|------|
| Agua   | 4179                             | 997                           | 855$\times 10^{-6}$            | 0.613                         | 5.83 |

: Propiedades termofísicas del agua en función de su temperatura promedio. {.striped .hover}

Responda lo siguiente:

1. Encuentre el flujo másico de vapor.
2. Encuentre la temperatura de salida del flujo refrigerante
3. Utilice método NTU para encontrar el largo de los tubos necesario para este sistema. Considere que se conocen los coeficientes de transferencia de calor para la carcasa. Para la zona de enfriamiento $h_{c,A} = 14200~\text{W/m}^2\cdot\text{K}$ y para la zona de condensación $h_{c,B} = 10800~\text{W/m}^2\cdot\text{K}$.
4. Encuentre las péridas de carga asociada a los tubos (Considere solo péridas por fricción) y la energía necesaria para bombear el agua refrigerante por todos los tubos. Considere para sus cálculos:

$$
P = \frac{\Delta p\dot{m}}{\rho}
$$

## Solución

<button class="btn btn-success" data-bs-toggle="collapse" href="#e06_2-sol" aria-expanded="false">Mostrar solución</button>

::: {#e06_2-sol .collapse .multi-collapse}

```{python}
#Paquetes utilizados
from numpy import pi, log, sqrt
import handcalcs.render
handcalcs.set_option("latex_block_start", "$$")
handcalcs.set_option("latex_block_end", "$$")
```

### Inciso 1 y 2

Tanto el flujo de vapor como la temperatura de salida del flujo refrigerante los podemos encontrar mediante el balance general de calor.

$$
q = c_p\dot{m}\Delta T
$$

Para el flujo de vapor que circula por la carcasa se debe considerar el fenómeno de enfriamiento y de condensación.

$$
q = q_A + q_B = \dot{m}_h\left(c_{p,h}\left(T_{i,h}-T^{sat}\right)+h_{fg}\right)
$$

```{python}
%%render params
q = 2e9 #W
c_ph = 2158 #J/kg$\cdot$K
T_ih = 130 #$^\circ$C
T_sat = 100 #$^\circ$C
h_fg = 2183*1000 #J/kg
```

```{python}
%%render long
m_h = q/(c_ph*(T_ih-T_sat)+h_fg) #kg/s
```

Mientras que para el flujo refrigerante debemos considerar que, el flujo total que pasará por todos los tubos, será:

$$
\dot{m}_c = \frac{N_t}{n}\times\dot{m}_{tubo}
$$

```{python}
%%render params
c_pc = 4179 #J/kg$\cdot$K
N_t = 27000
m_tubo = 1 #kg/s
m_c = (N_t/2)*m_tubo #kg/s
T_ic = 20 #$^\circ$C
```

```{python}
%%render long
T_oc = q/(m_c*c_pc) + T_ic #$^\circ$C
```

### Inciso 3

Primero que nada, al existir condensación, debemos separar el intercambiador de calor en dos partes para un análisis NTU. La primera parte $A$ considera el efecto de enfriamiento del vapor, mientras que la parte $B$ el efecto de condensación. Siempre que dividamos nuestro intercambiador debemos encontrar las temperaturas de entrada y salida de nuestras secciones. Para el flujo condensante será:

$$
T_{i,h}^A = 130~\text{°C} \hspace{0.5cm} T_{o,h}^A = 100~\text{°C} \hspace{2cm} T_{i,h}^B = 100~\text{°C} = T_{o,h}^B
$$

Mientras que para el fluido refrigerante:

$$
T_{i,c}^B = 20~\text{°C} \hspace{2cm} T_{o,c}^B = T_{i,c}^A \hspace{2cm} T_{o,c}^A = 55.451~\text{°C}
$$

Podemos calcular la temperatura de salida de $A$ con $q_A$ o la temperatura de $B$ con $q_B$.

```{python}
%%render long
## Usando B:
T_icB = T_ic #$^\circ$C
q_B = m_h*h_fg #W
T_ocB = q_B/(m_c*c_pc) + T_icB #$^\circ$C
## De igual forma, usando A:
T_ocA = T_oc #$^\circ$C
q_A = m_h*c_ph*(T_ih-T_sat) #W
T_icA = T_ocA - q_A/(m_c*c_pc) #$^\circ$C
```

**Análisis de *A***

Para la primera etapa:

$$
C_h = \dot{m}_h\cdot c_{p,h} \hspace{2cm} C_c = \dot{m}_c\cdot c_{p,c}
$$

Tal que,

$$
C_{r,A} = \frac{C_{min,A}}{C_{max,A}}
$$

```{python}
%%render long
C_h = m_h*c_ph #W/K
C_c = m_c*c_pc #W/K
C_rA = C_h/C_c
```

Luego, podemos obtener $\varepsilon_A$ y $NTU_A$ para flujos contra-corriente.

```{python}
%%render long
epsilon_A = q_A/(C_h*(T_ih-T_icA))
E_A = (2-epsilon_A*(1+C_rA))/(epsilon_A*sqrt(1+C_rA**2))
NTU_A = 1/sqrt(1+C_rA**2)*log((E_A+1)/(E_A-1))
```

Entonces el área requerida para la transferencia de calor:

$$
A_A = \frac{NTU_AC_{min,A}}{U_A}
$$

Para encontrar el coeficiente global de transferencia de masa en la zona de enfriamiento, debemos obtener el coeficiente local de transferencia de masa por el lado de los tubos.

$$
U_A = \left(\frac{d_i}{d_eh_{i,A}}+ \frac{d_i}{2 k_p}\ln\left(\frac{d_i}{d_e}\right) +\frac{1}{h_{c,A}}\right)^{-1}
$$

Se obtiene el coeficiente local de transferencia de calor de la misma forma que se haría para tubos.

$$
Re_D = \frac{G_td_i}{\mu}
$$

$$
G_t = \frac{\dot{m}}{a_t} = \frac{\frac{N_t}{n}\dot{m}_{tubo}}{\frac{N_t}{n}\left(\frac{\pi d_i^2}{4}\right)} = \frac{4\dot{m}_{tubo}}{\pi d_i^2} 
$$

Luego el número de Reynolds será:

$$
Re_D = \frac{4\dot{m}_{tubo}}{\pi d_i\mu}
$$

```{python}
%%render long
mu = 855e-6 #N$\cdot$s/m$^2$
d_i = 0.026 #m
Re_D = (4*m_tubo)/(pi*d_i*mu)
```

Para flujos turbulentos, tenemos que el número de Nusselt utilizamos la ecuación de Sieder-Tate bajo el supuesto $\mu\approx\mu_s$.

```{python}
%%render long
Pr = 5.83
Nusselt_D = 0.027*Re_D**0.8*Pr**(1/3)
```

```{python}
%%render long
k = 0.613 #W/m$\cdot$K
h_i = Nusselt_D*(k/d_i) #W/m$^2\cdot$K
```

Por último calculamos $U_A$ a partir de los coeficientes locales y luego despejamos el área de transferencia $A_A$.

```{python}
%%render long
h_cA = 14200 #W/m$^2\cdot$K
k_p = 53 #W/m$\cdot$K
d_e = 0.03 #m
U_A = (d_i/(d_e*h_i) + d_i/(2*k_p)*log(d_i/d_e) + 1/h_cA)**-1 #W/m$^2\cdot$K
A_A = (NTU_A*C_h)/U_A #m$^2$
```

**Análisis de *B***

Para $B$ consideramos que el proceso de condensación libera tanta energía tal que $C_h=\infty$. Luego, $C_{r,B} = 0$.

```{python}
%%render long
C_rB = 0
epsilon_B = q_B/(C_c*(T_sat-T_icB))
E_B = (2-epsilon_B)/epsilon_B
NTU_B = log((E_B+1)/(E_B-1))
```

Luego para $U_B$, $h_o$ será el mismo.

```{python}
%%render long
h_cB = 10800 #W/m$^2\cdot$K
U_B = (d_i/(d_e*h_i) + d_i/(2*k_p)*log(d_i/d_e) + 1/h_cB)**-1 #W/m$^2\cdot$K
A_B = (NTU_B*C_c)/U_B #m$^2$
```

Por último, sumamos las áreas y despejamos el largo de los tubos.

$$
A = \frac{N_t}{n}\times 2\pi d_iL
$$

```{python}
%%render long
A = A_A + A_B #m$^2$
L = A/(N_t/2*pi*d_i) #m
```

### Inciso 4

Para las pérdidas de fricción en un tubo, podemos calcular el factor de fricción mediante la ecuación de Nevers. La caida de presión asociada será:

$$
\frac{\Delta p}{\rho} = 4f\left(\frac{Lu_t}{2D}\right)
$$

Donde $u_t$ es la velocidad promedio en los tubos.

$$
u_t = \frac{4\dot{m}_{tubo}}{\rho\pi d_i^2}
$$

```{python}
%%render long
epsilon = 0.046
rho = 997 #kg/m$^3$
f = 0.001375*(1+(2*10**4*(epsilon/d_i)+(10**6/Re_D))**(1/3))
u_t = (4*m_tubo)/(rho*pi*d_i**2) #m/s
Delta_P = 4*f*((L*u_t*rho)/(2*d_i)) #N/m$^2$
```

Para la potencia de la bomba, se utiliza la ecuación proporcionada.

```{python}
%%render long
P = (Delta_P*m_c)/rho #W
```

La potencia total requerida para mover todo el líquido por los tubos en el intercambiador será $474.0~\text{kW}$.

:::